Add UI for the school library
duskotmane/school-library pull request #4
Opened 2023-07-28 16:26 UTC by otmaneechchafyky

# Features 🌟 

- [ ] List all books.
- [ ] List all people.
- [ ] Create a person (teacher or student, not a plain Person).
- [ ] Create a book.
- [ ] Create a rental.
- [ ] List all rentals for a given person id.
- [ ] Present the user with a list of options to perform.
- [ ] Lets users choose an option.
- [ ] Have a way to quit the app.

2023-07-28 19:07 UTC, brytebee requested changes
Hi, @otmaneechchafyky 👋,

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great UI design.✔️
- App functions as it should.✔️
- Good job taking inputs from users.✔️
- Excellent use of the prompt to direct the flow of the app.✔️

##

Good job so far coming so far with the progress you've made! 💪💪
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-28 19:07 UTC, brytebee commented on app.rb
> +    people_info = @people.map do |person|
Same as above.

2023-07-28 19:07 UTC, brytebee commented on app.rb
> +    book_info = @books.map do |book|
- [ ] **Optional:**
It could be an excellent experience to display a message to a user if no book was in the collection.

2023-07-28 19:07 UTC, brytebee commented on app.rb
> +    @rentals.each do |rental|
Same as above.

2023-07-28 19:07 UTC, brytebee commented on main.rb
> +      puts 'Thank you for using this app!'
The app ends when any other is pressed, this isn't good. Kindly ensure that the app end when the "7" key is pressed.

2023-07-29 00:59 UTC, Owusu-Desmond approved these changes
Hi @otmaneechchafyky , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-02 02:42 UTC, merged